### PR TITLE
Allow the virtualenv name to be passed as an optional argument to the script.

### PR DESCRIPTION
**Pull request by cobusc**

### CODE REVIEW

**Comment by jbeyers** [comment]
No problem in principle, but we're gonna litter .gitignore with all the creative virtualenv names :-)

**Comment by cobusc** [comment]
@jbeyers Our `.gitignore` should stay as is. In projects generated using the skeleton people can choose to replace `ve` with `mykewlvirtualenvname` if they want. That is only the one use-case though. I like the fact that I can create a `play` virtualenv quickly if I want to play around with something, in which case the `.gitignore` does not feature as the virtual envireonment is only temporary.

**Comment by hedleyroos** [comment]
Why is Travis failing?

**Comment by hedleyroos** [comment]
Oh it's happy now :)

**Pull request closed without merging**
